### ISSUE TITLE
email sign-up for people interested in working at the CFPB

### ISSUE THREAD

**Issue by benguhin** [cfpb/cfpb.github.io#46]
@Scotchester

**Comment by jimmynotjim** [comment]
:+1: It would be nice to have something to point people to, even if we don't have an open position at this exact moment.

**Comment by Scotchester** [comment]
@KimberlyMunoz has volunteered to take this on. Kim, please let me know if you need any assistance getting started with the codebase.

**Comment by KimberlyMunoz** [comment]
Just got this set up locally. Adding the form be too hard, but I'll need some help getting it to point to the same place as the signup form the the T&I recruiting site.

Any preferences on front page this should go?

+ As a section, similar to articles or repositories.
+ As a link under "We'd like to share our work with you" next to "Learn More".
+ Replacing the "Off the Press" sidebar in the top section.

I'm leaning towards replacing the "Off the Press" section, since we already have articles below.

**Comment by KimberlyMunoz** [comment]
Closing this issue since we have a solution in place to get emails to our hiring team.
